### ISSUE TITLE
Login/Signup Flow

### ISSUE THREAD

**Issue by kronaemmanuel** [Jadugars/versity#1]
Improvements required:

- [ ] Add OAuth with Google, Microsoft
- [ ] Don't let user click on "Sign Up" or "Login" button until they have filled a form
- [ ] Display a spinning loading icon while the information is being sent to the API
- [x] Change the error handler to display more user-understandable errors
- [ ] Handle error if the user loses internet connection
- [ ] Add "Remember Me" functionality
- [ ] Add "Forgot password" functionality
- [ ] Customize email templates on Firebase to our own
- [ ] Add "Resend Email" after 30 sec on SignUp page
- [ ] Verify that user's email is verified before letting them sign in to the app
